name: Publish to GitHub Pages
on:
  push:
    branches:
        - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: fabacab/jekyll-builder-for-github-pages-action@builder-3.8
          with:
            secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
            pre_build_commands: gem install bundler

