name: Build the site
on:
  push:
     branches:
       - main
jobs:
   urlsup:
     runs-on: ubuntu-latest
     steps:
         - uses: actions/checkout@v2
         - uses: simeg/urlsup-action@v1.0.0
           with:
                args: "**/*.md _config.yml --white-list \"https://drive.google.com\""

